DROP TABLE IF EXISTS T_OC_DATAHOST;

CREATE TABLE T_OC_DATAHOST(
GUID VARCHAR(32) NOT NULL
,NAME VARCHAR(50)
,MIN_CON VARCHAR(10)
,MAX_CON VARCHAR(10)
,BALANCE VARCHAR(10)
,HEARBEAT VARCHAR(200)
,CREATE_TIME datetime
,CREATE_USER VARCHAR(20)
,DBDRIVER VARCHAR(20)
,DBTYPE VARCHAR(10)
   
);



DROP TABLE IF EXISTS T_OC_DATAHOSTMAP;

CREATE TABLE T_OC_DATAHOSTMAP(
GUID VARCHAR(32) NOT NULL
,DATAHOST VARCHAR(20)
,HOST VARCHAR(20)
   
);

DROP TABLE IF EXISTS T_OC_DATANODE;

CREATE TABLE T_OC_DATANODE(
GUID VARCHAR(32) NOT NULL
,NAME VARCHAR(50) NOT NULL
,DATAHOST VARCHAR(20) NOT NULL
,`DATABASE` VARCHAR(20) NOT NULL
,CREATE_TIME datetime
,CREATE_USER VARCHAR(20)
   
);

DROP TABLE IF EXISTS T_OC_FUNCTION;

CREATE TABLE T_OC_FUNCTION
(
  GUID        VARCHAR(32) not null,
  NAME        VARCHAR(20),
  CLASS       VARCHAR(200),
  MAP_FILE    VARCHAR(100),
  CREATE_TIME DATE,
  CREATE_USER VARCHAR(20)
);

DROP TABLE IF EXISTS T_OC_FUNCTION_PARAM;

CREATE TABLE T_OC_FUNCTION_PARAM(
PARAM_VALUE Varchar(200) NOT NULL
,PARAM_KEY Varchar(20) NOT NULL
,FUNCTION_NAME Varchar(20) NOT NULL
,guid varchar(32)
   
);

DROP TABLE IF EXISTS T_OC_HOST;

CREATE TABLE T_OC_HOST(
GUID VARCHAR(32) UNIQUE NOT NULL
,HOST VARCHAR(30)
,URL VARCHAR(50)
,CREATE_TIME DATE
,CREATE_USER VARCHAR(20)
,D_USER VARCHAR(20)
,PASSWORD VARCHAR(50)
,PARENT_HOST VARCHAR(30)
,STATE VARCHAR(10)
   
);

DROP TABLE IF EXISTS T_OC_MYCAT;

CREATE TABLE T_OC_MYCAT
(
  GUID        VARCHAR(32) not null,
  PARAM_NAME  VARCHAR(50),
  PARAM_VALUE VARCHAR(50),
  RAMARK      VARCHAR(1000),
  CREATE_TIME DATE,
  CREATE_USER VARCHAR(20)
);

DROP TABLE IF EXISTS T_OC_SCHEMA;

CREATE TABLE T_OC_SCHEMA
(
  GUID        VARCHAR(32) not null,
  NAME        VARCHAR(20),
  CREATE_TIME DATE,
  CREATE_USER VARCHAR(20)
);


DROP TABLE IF EXISTS T_OC_SCHEMA_MAP;

CREATE TABLE T_OC_SCHEMA_MAP
(
  GUID        VARCHAR(32) not null,
  SCHEMA_NAME VARCHAR(20),
  TABLE_NAME  VARCHAR(20)
);


DROP TABLE IF EXISTS T_OC_TABLE;

CREATE TABLE T_OC_TABLE(
GUID VARCHAR(32) NOT NULL
,NAME VARCHAR(20) NOT NULL
,TYPE VARCHAR(10) NOT NULL
,DATANODE VARCHAR(100)
,RULE VARCHAR(100)
,PARENT_NAME VARCHAR(32)
,JOINKEY VARCHAR(20)
,PARENTKEY VARCHAR(30)
,CREATE_TIME DATE
,CREATE_USER VARCHAR(20)
,state varchar(10)
   
);


DROP TABLE IF EXISTS T_OC_TABLERULE;

CREATE TABLE T_OC_TABLERULE
(
  GUID        VARCHAR(32),
  NAME        VARCHAR(20),
  COLUMNS     VARCHAR(100),
  ALGORITHM   VARCHAR(20),
  CREATE_TIME DATE,
  CREATE_USER VARCHAR(20)
);


DROP TABLE IF EXISTS T_OC_USER;

CREATE TABLE T_OC_USER
(
  GUID        VARCHAR(32) not null,
  NAME        VARCHAR(20),
  PASSWORD    VARCHAR(20),
  APP_NAME    VARCHAR(50),
  APP_CODE    VARCHAR(20),
  CREATE_USER VARCHAR(20),
  CREATE_TIME TIMESTAMP(6),
  `SCHEMAS`     VARCHAR(100)
);

DROP TABLE IF EXISTS T_SYS_AUTHBUTTON;

CREATE TABLE T_SYS_AUTHBUTTON
(
  GUID        VARCHAR(36) not null,
  BUTTON_GUID VARCHAR(36),
  BUTTON_CODE VARCHAR(20),
  ROLE_GUID   VARCHAR(36),
  ROLE_CODE   VARCHAR(20),
  CREATE_TIME DATE  not null,
  CREATE_USER VARCHAR(20),
  REMARK      VARCHAR(200),
  MODIFY_TIME DATE,
  MODIFY_USER VARCHAR(20),
  BUTTON_NAME VARCHAR(100)
);

DROP TABLE IF EXISTS T_SYS_AUTHRESOUCE;

CREATE TABLE T_SYS_AUTHRESOUCE
(
  GUID          VARCHAR(36) not null,
  RESOURCE_GUID VARCHAR(100),
  RESOURCE_CODE VARCHAR(20),
  ROLE_GUID     VARCHAR(36),
  ROLE_CODE     VARCHAR(50),
  CREATE_TIME   DATE not null,
  CREATE_USER   VARCHAR(20),
  REMARK        VARCHAR(200),
  MODIFY_TIME   DATE,
  MODIFY_USER   VARCHAR(20)
);

DROP TABLE IF EXISTS T_SYS_AUTHUSER;

CREATE TABLE T_SYS_AUTHUSER
(
  USER_GUID   VARCHAR(36) not null,
  ROLE_GUID   VARCHAR(36) not null,
  CREATE_TIME DATE,
  CREATE_USER VARCHAR(20),
  MODIFY_TIME DATE,
  MODIFY_USER VARCHAR(20),
  USER_CODE   VARCHAR(20),
  ROLE_CODE   VARCHAR(40),
  GUID        VARCHAR(36)
);

DROP TABLE IF EXISTS T_SYS_CODE;

CREATE TABLE T_SYS_CODE
(
  GUID       VARCHAR(36) not null,
  VALUE      VARCHAR(30) not null,
  TEXT       VARCHAR(50) not null,
  CODE       VARCHAR(30) not null,
  PARENT     VARCHAR(30),
  REMARK     VARCHAR(200),
  CREATETIME DATE  not null,
  CREATEUSER VARCHAR(20)
);


DROP TABLE IF EXISTS T_SYS_FAVORITES;

CREATE TABLE T_SYS_FAVORITES
(
  GUID        VARCHAR(32) not null,
  LOGIN_ID    VARCHAR(20),
  PAGE_CODE   VARCHAR(20),
  CREATE_TIME DATE
);

DROP TABLE IF EXISTS T_SYS_GLOBALVARIABLE;

CREATE TABLE T_SYS_GLOBALVARIABLE
(
  GUID        VARCHAR(32) not null,
  CODE        VARCHAR(20),
  STATE       VARCHAR(2),
  TYPE        VARCHAR(10),
  REMARK      VARCHAR(200),
  CREATE_TIME DATE,
  CREATE_USER VARCHAR(20),
  MODIFY_USER VARCHAR(20),
  MODIFY_TIME DATE
);

DROP TABLE IF EXISTS T_SYS_MENU;

CREATE TABLE T_SYS_MENU
(
  GUID        VARCHAR(36) not null,
  CODE        VARCHAR(20),
  PARENT_CODE VARCHAR(20),
  PAGE_CODE   VARCHAR(200),
  REMARK      VARCHAR(100),
  CREATE_TIME DATE,
  CREATE_USER VARCHAR(20),
  STATUS      VARCHAR(10),
  SORT_INDEX  bigint,
  NAME        VARCHAR(50),
  STATE       VARCHAR(10)
);


DROP TABLE IF EXISTS T_SYS_MYBATIS;

CREATE TABLE T_SYS_MYBATIS
(
  GUID        VARCHAR(32) not null,
  NS_CODE     VARCHAR(20),
  NS_NAME     VARCHAR(200),
  ST_CODE     VARCHAR(20),
  ST_NAME     VARCHAR(200),
  REMARK      VARCHAR(200),
  CREATE_TIME DATE  not null,
  CREATE_USER VARCHAR(20)
);

DROP TABLE IF EXISTS T_SYS_ORG;

CREATE TABLE T_SYS_ORG
(
  GUID        VARCHAR(36) not null,
  ORG_CODE    VARCHAR(20) not null,
  ORG_NAME    VARCHAR(200) not null,
  PARENT_CODE VARCHAR(20),
  LEVELS      bigint,
  ALIVE_FLAG  bigint,
  CREATE_TIME DATE,
  CREATE_USER VARCHAR(20),
  STATE       VARCHAR(10)
);

DROP TABLE IF EXISTS T_SYS_PAGE;

CREATE TABLE T_SYS_PAGE
(
  GUID        VARCHAR(36) not null,
  CODE        VARCHAR(20) not null,
  URL         VARCHAR(200) not null,
  NAME        VARCHAR(50) not null,
  CREATE_TIME DATE,
  CREATE_USER VARCHAR(20),
  IS_CACHE    VARCHAR(10)
);

DROP TABLE IF EXISTS T_SYS_PARAM;

CREATE TABLE T_SYS_PARAM
(
  CODE    VARCHAR(50),
  NAME    VARCHAR(50),
  TYPE    VARCHAR(20),
  FLAG    VARCHAR(50),
  LENGTHS VARCHAR(20),
  ISNOT   VARCHAR(20)
);

DROP TABLE IF EXISTS T_SYS_ROLE;

CREATE TABLE T_SYS_ROLE
(
  GUID           VARCHAR(36) not null,
  ROLE_CODE      VARCHAR(40) not null,
  ROLE_NAME      VARCHAR(100),
  ROLE_TYPE_CODE VARCHAR(20) not null,
  ORG_CODE       VARCHAR(20) not null,
  CREATE_TIME    DATE,
  CREATE_USER    VARCHAR(20)
);

DROP TABLE IF EXISTS T_SYS_ROLETYPE;

CREATE TABLE T_SYS_ROLETYPE
(
  GUID            VARCHAR(36) not null,
  ROLE_TYPE_CODE  VARCHAR(20) not null,
  ROLE_TYPE_NAME  VARCHAR(100) not null,
  STATUS          bigint,
  REMARK          VARCHAR(200),
  SORT_INDEX      bigint,
  CREATE_TIME     DATE,
  CREATE_USER     VARCHAR(20),
  ROLE_TYPE_GROUP VARCHAR(20)
);

DROP TABLE IF EXISTS T_SYS_SERVICE;

CREATE TABLE T_SYS_SERVICE
(
  GUID         VARCHAR(36) not null,
  SERVICE_CODE VARCHAR(20) not null,
  METHOD_CODE  VARCHAR(20) not null,
  PACKAGE      VARCHAR(50) not null,
  REMARK       VARCHAR(200),
  CREATE_TIME  DATE not null,
  CREATE_USER  VARCHAR(20),
  SERVICE_NAME VARCHAR(20) not null,
  METHOD_NAME  VARCHAR(20) not null
);

DROP TABLE IF EXISTS T_SYS_SETUP;

CREATE TABLE T_SYS_SETUP
(
  GUID        VARCHAR(32) not null,
  FUN_NAME    VARCHAR(200),
  FUN_CODE    VARCHAR(30),
  FUN_DESC    VARCHAR(200),
  REMARK      VARCHAR(200),
  CREATE_USER VARCHAR(20),
  CREATE_TIME DATE,
  IS_DISPLAY  VARCHAR(10)
);


DROP TABLE IF EXISTS T_SYS_USER;

CREATE TABLE T_SYS_USER
(
  GUID         VARCHAR(36) not null,
  LOGIN_ID     VARCHAR(20) not null,
  NAME         VARCHAR(20) not null,
  PASSWORD     VARCHAR(32) not null,
  ALIVE_FLAG   VARCHAR(10),
  CREATE_TIME  DATE,
  CREATE_USER  VARCHAR(20),
  MOBILE_PHONE VARCHAR(15),
  ADDRESS      VARCHAR(200),
  AGE          bigint default '0',
  SEX          bigint default '0',
  SORT_INDEX   bigint,
  ORG_CODE     VARCHAR(20),
  IN_JOIN_TIME DATE,
  WORK_STATUS  bigint,
  E_MAIL       VARCHAR(50),
  IS_ONLINE    VARCHAR(10) default '0',
  IS_VERIFY    VARCHAR(10) default '1'
);

DROP TABLE IF EXISTS T_SYS_WHEREEX;

CREATE TABLE T_SYS_WHEREEX
(
  GUID            VARCHAR(32) not null,
  WHERE_NAME      VARCHAR(50),
  CODE            VARCHAR(30),
  `DESCRIBE`        VARCHAR(50),
  REMARK          VARCHAR(200),
  CREATE_TIME     DATE not null,
  CREATE_USER     VARCHAR(20),
  VALUE_TYPE      VARCHAR(30),
  VALUE_CODE      VARCHAR(30),
  VALUE_SERVICE   VARCHAR(30),
  VALUE_METHOD    VARCHAR(100),
  BIZ_COMBOX_ID   VARCHAR(30),
  BIZ_COMBOX_TEXT VARCHAR(30),
  EXTEND3         VARCHAR(50),
  EXTEND4         VARCHAR(50),
  EXTEND5         VARCHAR(50),
  BIZ_COLUMNS     VARCHAR(1000),
  SORT_INDEX      bigint,
  WHERE_CODE      VARCHAR(30)
);

CREATE INDEX OC_DATAHOST_INDEX On T_OC_DATANODE (
NAME );

CREATE INDEX oc_function_param On T_OC_FUNCTION_PARAM (
FUNCTION_NAME  ASC);


